[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "util"
path = "src/lib.rs"

[dependencies]
color-eyre = "0.6.2"
im = "15.1.0"
itertools = "0.10.1"
nom = "7.1.1"
